export const allVenues = [
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [{ url: 'https://www.facebook.com/mustpuudel/', title: 'Facebook' }],
    authorId: null,
    disabled: false,
    id: 'must-pudel-tallin',
    name: 'Must Puudel',
    description: null,
    address: 'Müürivahe Tänav 20, 10140 Tallinn, Estonia',
    coordinates: { latitude: 59.435307, longitude: 24.747145 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'joe-juice-hel',
    name: 'Joe & The Juice',
    description: 'Берешь фибре-эктив и кайфуешь. Лучшие соки в мире.',
    address: 'Aleksanterinkatu 52, 00100 Helsinki, Finland',
    coordinates: { latitude: 60.168558, longitude: 24.942722 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [
      { url: 'https://www.instagram.com/saviv.bistro', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'saviv-bistro-spb',
    name: 'Saviv Israeli Bistro',
    description:
      'Офигенный тальята-стейк, шикарная баранина, крутые локал-напитки',
    address: 'Большая Конюшенная ул., 9, Санкт-Петербург, 191186',
    coordinates: { latitude: 59.939993, longitude: 30.323792 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch'],
    links: [
      {
        url: 'https://www.instagram.com/baget.omlet.tomsk/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'baget-omlet-tomsk',
    name: 'Багет-Омлет',
    description: '',
    address: 'пр. Ленина, 55, Томск, Томская обл., 634050',
    coordinates: { latitude: 56.470144, longitude: 84.951775 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch'],
    links: [
      { url: 'https://www.instagram.com/ptichkacafe/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'ptichka-tomsk',
    name: 'Птичка',
    description: '',
    address: 'пр. Ленина, 81, Томск, Томская обл., 634050',
    coordinates: { latitude: 56.477662, longitude: 84.950667 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [
      {
        url: 'https://www.instagram.com/sparks_home_kitchen/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'sparks-nsb',
    name: 'Sparks Home Kitchen',
    description: null,
    address: 'ул. Ильича, 8, Новосибирск, Новосибирская обл., 630090',
    coordinates: { latitude: 54.840905, longitude: 83.093171 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'mr-tako-tomsk',
    name: 'Mr. Tako',
    description: '',
    address: 'ул. Усова, 6 ст12, Томск, Томская обл., 634034',
    coordinates: { latitude: 56.464398, longitude: 84.956101 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'blue-spice-protaras',
    name: 'Blue Spice',
    description: 'Отличная локал-кухня. Работает зимой!',
    address: null,
    coordinates: { latitude: 35.028754, longitude: 34.043779 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch'],
    links: [
      {
        url: 'https://www.instagram.com/pureenergyphuket/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'pure-energy-phuket',
    name: 'Pure Energy',
    description: null,
    address:
      '50/35, Soi Saiyan, Rural Road 4009, Rawai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.792911, longitude: 98.321489 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch'],
    links: [
      {
        url: 'https://www.instagram.com/boostcafe_phuket/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'boost-phuket',
    name: 'BOOST',
    description: null,
    address: '39/38 หม1, Rawai, Mueang Phuket District, Phuket 83120',
    coordinates: { latitude: 7.79064, longitude: 98.316771 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [{ url: 'https://www.instagram.com/cafexoho', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'xoho-tlv',
    name: 'CafeXoho',
    description: null,
    address: '17 Y.L. Gordon Street Tel Aviv, Israel',
    coordinates: { latitude: 32.168494, longitude: 34.84417 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/underthetreetlv/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'under-tree-tvl',
    name: 'Under The Tree',
    description: '',
    address: '202 Ben Yehuda Tel Aviv, Israel',
    coordinates: { latitude: 32.090204, longitude: 34.774161 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['breakfast', 'lunch', 'dinner', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/futurabistro/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'futura-petro-spb',
    name: 'ФУТУРА',
    description:
      'Каждый день новый ланч, волшебные завтраки и крутейшее меню ужинов. Пожалуй, лучшее заведение на Петроградке.',
    address: 'наб. Pеки Карповки, 5, корпус 36, Санкт-Петербург, 197022',
    coordinates: { latitude: 59.969163, longitude: 30.317302 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['dinner'],
    links: [
      { url: 'https://www.instagram.com/holyribsbar/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'holy-ribs-spb',
    name: 'Holy Ribs',
    description: 'Лучшие ребрышки Петербурга. Маленькой порции достаточно!',
    address: 'ул. Жуковского, 12, Санкт-Петербург, 191014',
    coordinates: { latitude: 59.936089, longitude: 30.353298 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [
      {
        url: 'https://www.instagram.com/cooperative_garage/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'coop-garage-spb',
    name: 'Co-op Garage',
    description: null,
    address: 'Гороховая ул., 47, Санкт-Петербург, 191023',
    coordinates: { latitude: 59.927082, longitude: 30.322698 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/coffee3spb/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'coffee-3-spb',
    name: 'Coffee 3',
    description:
      'Во-первых, это красиво — шикарный вид. А еще отличный кофе, вкусная еда и розетки для работы за ноутбуком.',
    address: 'Аптекарский пр., 4, Санкт-Петербург, 197022',
    coordinates: { latitude: 59.969801, longitude: 30.316628 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [
      { url: 'https://www.instagram.com/pitasstreetfood/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'pitas-spb',
    name: 'PITA’S',
    description: 'Традиционная питерская шаверма. Лучший PITA’s в городе.',
    address: 'наб. Pеки Карповки, 10, Санкт-Петербург, 197101',
    coordinates: { latitude: 59.967789, longitude: 30.312373 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [
      {
        url: 'https://www.instagram.com/7spicesstreetfood',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: '7specii-spb',
    name: '7 СПЕЦИЙ',
    description: 'Хорошая индийская еда. Тут острое — это правда острое.',
    address: 'Аптекарский пр., 4, Санкт-Петербург, 197022',
    coordinates: { latitude: 59.969695, longitude: 30.318328 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['breakfast'],
    links: [
      { url: 'https://www.instagram.com/followdreamers/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'dreamers-spb',
    name: 'Мечтатели',
    description: null,
    address: 'набережная реки Фонтанки, 11, Санкт-Петербург, 191023',
    coordinates: { latitude: 59.936894, longitude: 30.342886 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'https://instagram.com/o_petit', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'opetit-nev-spb',
    name: 'Ôpetit',
    description:
      'Небольшое кафе во Французском институте. Еды почти нет, зато хороший вид на Невский и приятный интерьер.',
    address: 'Невский пр., 12, Санкт-Петербург, 191186',
    coordinates: { latitude: 59.936871, longitude: 30.315737 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/frankmeat', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'frank-spb',
    name: 'FRANK',
    description: 'Номер #2 среди ребрышек Петербурга — отличное мясо.',
    address: 'Большой проспект П.С., 35 лит. А, St Petersburg, Russia, 197198',
    coordinates: { latitude: 59.959585, longitude: 30.302183 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/wilsonscafe/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'silsons-phuket',
    name: 'Wilson’s Cafe',
    description: null,
    address: '31, 44 Soi Saiyuan Rawai, Amphoe Mueang, Phuket 83100',
    coordinates: { latitude: 7.788176, longitude: 98.317201 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/harvestbyduo', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'harvest-spb',
    name: 'harvest.',
    description:
      'Высокая кухня — все блюда звучат страшно, но, на самом деле, вкусные. Крутейшие свежие соки.',
    address: 'пр. Добролюбова, 11, Санкт-Петербург, 197198',
    coordinates: { latitude: 59.949625, longitude: 30.301764 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/duoband', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'tartarbar-spb',
    name: 'Тартарбар',
    description:
      'Легендарный ресторан высокой кухни. Обязательно попробуй мусс из зобной железы.',
    address: 'Виленский пер., 15, Санкт-Петербург, 191014',
    coordinates: { latitude: 59.940057, longitude: 30.366371 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [{ url: 'https://instagram.com/kroocafe', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'droo-cafe-spb',
    name: 'KROO CAFE',
    description: null,
    address: 'Суворовский пр., 27/9, Санкт-Петербург, 191036',
    coordinates: { latitude: 59.937721, longitude: 30.374102 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'bite-drink'],
    links: [
      { url: 'https://instagram.com/andycoffee_spb', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'andy-apb',
    name: 'ЭНДИ КОФЕ',
    description: null,
    address:
      'Большой проспект П.С., 106, Санкт-Петербург, Ленинградская обл., 197022',
    coordinates: { latitude: 59.967668, longitude: 30.313279 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'dinner', 'bite-drink'],
    links: [
      { url: 'https://instagram.com/chocolatebar_spb', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'chocolate-spb',
    name: 'Шоколадный Бар',
    description:
      'Кафе в оранжерее, прямо сидишь среди деревьев в любое время года!',
    address: 'Каменноостровский пр., 42-А, Санкт-Петербург, 197101',
    coordinates: { latitude: 59.966626, longitude: 30.309853 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [
      { url: 'https://instagram.com/cakeandbreakfast', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'pancacke-spb',
    name: 'Pan&Cake',
    description: null,
    address: 'ул. Мира, 7Г, Санкт-Петербург, 197101',
    coordinates: { latitude: 59.959345, longitude: 30.314567 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [
      { url: 'https://instagram.com/oversize.pizza', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'oversize',
    name: 'OVERSIZE pizza club',
    description: 'Очень большая пицца. И вкусная.',
    address: 'Гражданская ул., 13-15, Санкт-Петербург, 190031',
    coordinates: { latitude: 59.928556, longitude: 30.312378 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/bekitzer_spb', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'bekitzer-spb',
    name: 'Bekitzer',
    description: null,
    address: 'Ул. Рубинштейна, 40/11, Санкт-Петербург, 191002',
    coordinates: { latitude: 59.926729, longitude: 30.342694 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [
      {
        url: 'https://www.instagram.com/tucanocoffee.spb/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'tucano-spb',
    name: 'Tucano',
    description:
      'Достойный кофе, хорошие завтраки и прекрасная атмосфера. Есть розетки для ноутбука.',
    address: 'Большой проспект П.С., 79, Санкт-Петербург, 197136',
    coordinates: { latitude: 59.966553, longitude: 30.31372 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/lobby.cafebar', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'lobby-msk',
    name: 'Лобби кафе бар',
    description: null,
    address: 'Большой Сухаревский пер., 25 стр 1, Москва, 107045',
    coordinates: { latitude: 55.770865, longitude: 37.631778 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['breakfast', 'dinner'],
    links: [
      { url: 'https://instagram.com/severyane.moscow', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'severyzne-msk',
    name: 'Северяне',
    description: null,
    address: 'Большая Никитская ул., 12, Москва, 125009',
    coordinates: { latitude: 55.756526, longitude: 37.606386 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'jack-chan-spb',
    name: 'Jack & Chan',
    description: 'Курица Кунг Пао тут особенная.',
    address: 'Инженерная ул., 7, Санкт-Петербург, 191011',
    coordinates: { latitude: 59.937326, longitude: 30.336883 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [
      { url: 'https://instagram.com/friends_social_club', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'dr-so-cl-msk',
    name: 'Friends Social Club',
    description: null,
    address: 'Кутузовский просп., 1/7, Москва, 121248',
    coordinates: { latitude: 55.750392, longitude: 37.571266 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'bite-drink'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'starbooks-tomsk',
    name: 'Starbooks',
    description: 'Неповторимый оригинал!',
    address: 'пр. Ленина, 36 корпус 9, Томск, Томская обл., 634050',
    coordinates: { latitude: 56.469664, longitude: 84.946172 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [
      { url: 'https://www.instagram.com/makelovepizza/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'makelove-tomsk',
    name: 'Make Love Pizza',
    description: null,
    address: 'пр. Ленина, 85a, Томск, Томская обл., 634050',
    coordinates: { latitude: 56.478291, longitude: 84.950273 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/reka_827', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'reka-romsk',
    name: 'река 827',
    description: null,
    address: 'пер. Кооперативный, 2, Томск, Томская обл., 634009',
    coordinates: { latitude: 56.490377, longitude: 84.943698 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/myasoroob', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'myacsoroob-nsk',
    name: 'МясоRoob',
    description: null,
    address:
      'ул. Вокзальная Магистраль, 16, Новосибирск, Новосибирская обл., 630099',
    coordinates: { latitude: 55.03138, longitude: 82.91434 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      { url: 'https://instagram.com/organic.coffee', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'organic-nsk',
    name: 'Organic.Coffee',
    description: null,
    address: 'Красный пр-т., 86 б, Новосибирск, Новосибирская обл., 630105',
    coordinates: { latitude: 55.049457, longitude: 82.9158 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [
      { url: 'https://instagram.com/pitchii_coffee', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'pitchi-nsk',
    name: 'PITCHII COFFEE',
    description: '',
    address: 'ул. Ленина, 9, Новосибирск, Новосибирская обл., 630099',
    coordinates: { latitude: 55.02931, longitude: 82.913355 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'https://instagram.com/ladureerussia', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'laduree-msk',
    name: 'Ladurée',
    description: null,
    address: 'Nikolskaya, 5/1 build. 3, Moscow, Russia, 109012',
    coordinates: { latitude: 55.755771, longitude: 37.619776 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'https://instagram.com/varavcafe', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'varav-tallin',
    name: 'Värav',
    description: null,
    address: 'Väike Rannavärav 4, 10111 Tallinn, Estonia',
    coordinates: { latitude: 59.441513, longitude: 24.750721 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [{ url: 'https://instagram.com/t35bakery', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 't-25-tallin',
    name: 'T35 — The Breakfast Club',
    description: null,
    address: 'Tööstuse 35, 10411 Tallinn, Estonia',
    coordinates: { latitude: 59.446864, longitude: 24.730582 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'marcipan-tallin',
    name: 'Kalevi martsipani muuseumituba',
    description: 'Обязательно сядь на втором этаже 😉',
    address: 'Pikk 16, 10123 Tallinn, Estonia',
    coordinates: { latitude: 59.438332, longitude: 24.745521 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch'],
    links: [{ url: 'https://instagram.com/beze_abakan', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'beze-abakan',
    name: 'Безе',
    description: null,
    address: 'ул. Кирова, 112, Абакан, Респ. Хакасия, 655017',
    coordinates: { latitude: 53.727508, longitude: 91.436737 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'muslim-phuket',
    name: 'Мусульмане',
    description:
      'Халялньная тайская еда, большие порции. Одно из немногих мест, где не страшно есть тру-тайскую еду.',
    address:
      'ราไวย์ Tambon Rawai, Mueang Phuket District, Phuket 83100, Таиланд',
    coordinates: { latitude: 7.791711, longitude: 98.319069 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink', 'breakfast'],
    links: [
      {
        url: 'https://instagram.com/booster_coffee?igshid=1b16rydw8d99s',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: '8ptxj14tyl1715vnnddw',
    name: 'Booster ',
    description: 'Модная кафешка в центре Абакана. ',
    address: '',
    coordinates: { latitude: 53.722247, longitude: 91.4460922 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      {
        url: 'https://instagram.com/homebakeryshop?igshid=im5gn7nrsiyt',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: '8siwtrltrlqmglayrxy9',
    name: 'Home Bakery Shop',
    description: 'Крутая кондитерская с невероятными десертами. ',
    address: '',
    coordinates: { latitude: 53.7406011, longitude: 91.4198595 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'https://www.torrysicecream.com', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'kab5fh71pug8xar167mf',
    name: "Torry's Ice Cream",
    description:
      'Большой выбор мороженого (особенно крутое локал-тайское), интересные напитки, приятная атмосфера.',
    address:
      '16 Soi Rommani, Tumbon Talad Yai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.885385, longitude: 98.389225 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [
      {
        url: 'https://instagram.com/mojitobarandgrillcyprus',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'mojito-protaras',
    name: 'Mojito',
    description: 'Царские завтраки и обеды (в комплекте огромный бокал вина).',
    address: '18 Aphrodite street Pernera Protaras, 5296, Cyprus',
    coordinates: { latitude: 35.02716, longitude: 34.041468 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '4o6edxfarg4u2butql2i',
    name: 'The Shack',
    description: 'Здоровая еда и шикарные соки.',
    address: '4233 ราไวย์, Rawai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.788973, longitude: 98.317294 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [{ url: 'http://www.gallerycafesphuket.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'qsd0padd1xog18vtz3d0',
    name: 'Gallery Cafe',
    description: 'Обычное, но приятное кафе.',
    address: '39 12 ซอย ไสยวน 1 Rawai, Mueang Phuket District, Phuket 83130',
    coordinates: {
      latitude: 7.79139,
      longitude: 98.316648,
    },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink', 'breakfast'],
    links: [
      {
        url: 'https://instagram.com/madespressoteam?igshid=kdvrz69wgmhn',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: 'uayoeemesqv075jll725',
    name: 'Mad Espresso Team',
    description:
      'Уютные кафешки, где можно позавтракать, просто перекусить и выпить чаю/кофе. Там красиво и модно.',
    address: '2-я Советская ул., 27, Санкт-Петербург, Россия, 191024',
    coordinates: { latitude: 59.930232, longitude: 30.372167 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [
      {
        url: 'https://instagram.com/cake_shop_spb?igshid=1i5rhcolqbjwc',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: 'bs26avtnz18ijvmn9jje',
    name: 'Cake Shop',
    description:
      'Небольшая кофейня с очень классными сладостями. Можно позавтракать.',
    address: 'ул. Блохина, 27, Санкт-Петербург, Россия, 197198',
    coordinates: { latitude: 59.9524593, longitude: 30.2949474 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [
      {
        url: 'https://www.instagram.com/sri.theshophouse/',
        title: 'Instagram',
      },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'wa91o1jr0f4h8l9qvavk',
    name: 'sri the shophouse',
    description:
      'Очень красиво и очень вкусно. Совсем небольшое меню, но все что нужно есть.',
    address:
      '125 Soi Soon Utis, Tambon Talat Nuea, Mueang Phuket District, Chang Wat Phuket 83000',
    coordinates: { latitude: 7.885982, longitude: 98.386357 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'ij20yg7mnt1h8tzd84qg',
    name: 'hom•mes',
    description: 'Небольшая милая кофейня с прекрасными дессертами.',
    address: '145 Soi Suksan 1, Rawai, Mueang Phuket District, Phuket 83130',
    coordinates: { latitude: 7.816986, longitude: 98.331658 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [
      { url: 'https://www.friends-forever.ru/#gallery-1', title: 'Сайт' },
      {
        url: 'https://www.instagram.com/friends_forever_company/',
        title: 'Instagram',
      },
    ],
    authorId: 'tra4uu83tff',
    disabled: false,
    id: 'oct4sp1ublgbulnxym1e',
    name: 'Breakfast Cafe',
    description:
      'Панкейки с соусом и не только. Вкусно, сладко, большие порции, хорошая локация. ',
    address: 'Малая Никитская ул., 2/1с1, Москва',
    coordinates: { latitude: 55.757989, longitude: 37.597461 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'g0j80nh6r5c3mpfjt232',
    name: 'The Circle Coffee Boutique',
    description:
      'Хорошее место с приятным интерьером и замечательными завтраками.',
    address:
      '27/7 Chao Fah Tawan Tok Rd, Chalong, Mueang Phuket District, Phuket 83130',
    coordinates: { latitude: 7.84662, longitude: 98.334613 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '5okn0v6jo0oo1tuzfvr7',
    name: 'Aram',
    description: 'Крутой интерьер, замечательный кофе и очень вкусные блины.',
    address: 'Kata Rd, Karon, Mueang Phuket District, Phuket 83100',
    coordinates: { latitude: 7.817302, longitude: 98.300998 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      {
        url: 'https://instagram.com/grnhs.abakan?igshid=aww0cpxtck12',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: 'i4neuejvrshpkpul0917',
    name: 'Green House',
    description:
      'Небольшая сеть кофейн, но самая популярная в Абакане. Самая классная по атмосфере в гостинице «Дружба».',
    address: 'ул. Дружбы Народов, 2, Абакан, Респ. Хакасия, Россия, 655016',
    coordinates: { latitude: 53.7362092, longitude: 91.4373878 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'raw-cafe-phuket',
    name: 'Raw Cafe & Vegan Bistro',
    description:
      'Классные напитки и десерты, еда очень веганская и только сырая.',
    address:
      '99/1 หมู่ที่7 Wiset Rd, Rawai, Mueang Phuket District, Phuket 83130',
    coordinates: { latitude: 7.793629, longitude: 98.330923 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      { url: 'https://instagram.com/kgallerybookcafe', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'kgallery-spb',
    name: 'KGallery',
    description: 'Кафе в картинной галлереи.',
    address: 'набережная реки Фонтанки, 24, Санкт-Петербург, 191028',
    coordinates: { latitude: 59.939941, longitude: 30.342163 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'esplanad-hel',
    name: 'Café Esplanad',
    description: 'Салат с лососем — тут это основное блюдо, и очень вкусное.',
    address: 'Pohjoisesplanadi 37, 00100 Helsinki, Finland',
    coordinates: { latitude: 60.167805, longitude: 24.944519 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/burgerandcrab', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'crab-spb',
    name: 'Burger&Crab',
    description:
      'Хорошие ноги крабов, бургеры с крабами и вообще все из крабов.',
    address: 'ул. Рубинштейна, 40, Санкт-Петербург, 191002',
    coordinates: { latitude: 59.92663, longitude: 30.342756 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [
      { url: 'https://www.instagram.com/rebrotomsk/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'rebro-tomsk',
    name: '#RE:BRO',
    description: 'Кайфовые бургеры.',
    address: 'пр. Ленина, 77а, Томск, Томская обл., 634050',
    coordinates: { latitude: 56.477081, longitude: 84.950328 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'bite-drink'],
    links: [{ url: 'https://instagram.com/o_petit', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'opetit-petr-spb',
    name: 'Ôpetit',
    description:
      'Абсолютно прекрасное место — вкусно, красиво, есть места для работы с ноутбуком.',
    address: 'ул. Блохина, 23, Санкт-Петербург, 197198',
    coordinates: { latitude: 59.952325, longitude: 30.297282 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://www.instagram.com/pio_nero/', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'pionero-spb',
    name: 'Pio Nero',
    description: 'Паста, пицца и вино.',
    address: 'Пионерская ул., 5, Санкт-Петербург, 197198',
    coordinates: { latitude: 59.955869, longitude: 30.295448 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'https://instagram.com/surfcoffeespb', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'surf-spb',
    name: 'Surf Coffee',
    description:
      'Самый классный SurfCoffee Петербурга, маленький и очень уютный. ',
    address: 'Гороховая ул., 34, Санкт-Петербург, 191023',
    coordinates: { latitude: 59.929288, longitude: 30.321173 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [
      {
        url: 'https://www.instagram.com/theburgerlab.tomsk/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'burger-lab-tomsk',
    name: 'The Burger Lab.',
    description: 'Изысканные бургеры, крутые завтраки, замечательные стейки.',
    address: 'ул. Розы Люксембург, 16, Томск, Томская обл., 634009',
    coordinates: { latitude: 56.49152, longitude: 84.950642 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/duoband', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'duo-spb',
    name: 'Duo',
    description: 'Небольшой очень уютный ресторан высокой кухни.',
    address: 'Кирочная ул., 8А, Санкт-Петербург, 191028',
    coordinates: { latitude: 59.944255, longitude: 30.351679 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [
      { url: 'https://vk.com/harekrishnacafe', title: 'Сайт' },
      { url: 'https://www.instagram.com/jiva_project/', title: 'Instagram' },
    ],
    authorId: 'r5v1qrpmsvg',
    disabled: false,
    id: 'eyt9atnmzanb5ku8yv1y',
    name: 'Jiva Burgers',
    description:
      'Кришнаитское кафе — всё по вегану. Их фишка — чудесные бургеры в виде конструктора (сам выбираешь вид хлеба/котлеты/топпингов). Есть и другая еда, тоже крутая. Очень недорого и душевно.',
    address: 'наб. канала Грибоедова, 49, Санкт-Петербург, 190031',
    coordinates: { latitude: 59.930424, longitude: 30.318322 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['breakfast', 'lunch', 'dinner'],
    links: [{ url: 'https://www.instagram.com/mogg/', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'mogg-berlin',
    name: 'Mogg',
    description: 'Очень вкусное мясо — колбаски, бутерброды.',
    address: 'Auguststraße 11-13, 10117 Berlin, Germany',
    coordinates: { latitude: 52.526505, longitude: 13.394451 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['breakfast', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/stimcoffeehome/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'stim-spb',
    name: 'STIM',
    description: 'Лучшие сырники эва!',
    address: 'Гражданская ул., 13-15, Санкт-Петербург, 190031',
    coordinates: { latitude: 59.92842, longitude: 30.311972 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'stammtisch-phuket',
    name: 'Stammtisch',
    description: 'Очень грязно, очень вкусно, немножко по-немецки.',
    address: '',
    coordinates: { latitude: 7.784508, longitude: 98.317311 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'lido-tallin',
    name: 'Lido',
    description:
      'Шикарная столовая. Тут дешево и вкусно, классный суп с клецами.',
    address: 'Estonia puiestee 9, 10143 Tallinn, Estonia',
    coordinates: { latitude: 59.433537, longitude: 24.750984 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [
      { url: 'https://www.instagram.com/tablecafemoscow/', title: 'Instagram' },
    ],
    authorId: 'tra4uu83tff',
    disabled: false,
    id: 'woyk8byle33i4pzphcwj',
    name: 'Table cafe',
    description:
      'Разные вкусные завтраки целый день. Каши, тосты, яйца, гранолы, драники. Очень мало места внутри, нет брони. Можно с животными.',
    address: 'Лесная ул., 45, Москва',
    coordinates: { latitude: 55.780971, longitude: 37.591466 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [
      { url: 'https://www.instagram.com/eggsellent.ru/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'eggselent-spb',
    name: 'Кулинарная группировка «ЯЙЦА»',
    description: 'Кайфовые завтраки из яиц.',
    address:
      'Большой проспект Васильевского острова, 16, Санкт-Петербург, 199034',
    coordinates: { latitude: 59.939453, longitude: 30.285249 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [{ url: 'https://www.kstb.cafe', title: 'Сайт' }],
    authorId: null,
    disabled: false,
    id: 'kysybyi-kazan',
    name: 'Кыстыбый',
    description: 'Татарский фастфуд — вкусно, халяльно, много мяса.',
    address: 'Спартаковская ул., 23, Казань, Респ. Татарстан, 420107',
    coordinates: { latitude: 55.78031, longitude: 49.12982 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['breakfast', 'lunch', 'dinner', 'bite-drink'],
    links: [
      { url: 'https://www.instagram.com/sightcoffeedine/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'sight-spb',
    name: 'Sight',
    description: 'Восхитительный кофе и изысканная еда.',
    address: 'Большая Зеленина ул., 24, Санкт-Петербург, 197110',
    coordinates: { latitude: 59.962845, longitude: 30.28636 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'rjzbct97gi9h9ktsm1j8',
    name: 'HOGFATHER BBQ & MORE',
    description: 'Ребрышки, грудинка и бургеры.',
    address: '36/9 m2 soi Palai chalong muang Phuket 83130',
    coordinates: { latitude: 7.84394, longitude: 98.350869 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['breakfast', 'bite-drink'],
    links: [{ url: 'https://instagram.com/smenacafe', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'smena-spb',
    name: 'СМЕНА',
    description: 'Обязательно попробуй творожники.',
    address: 'Басков пер., 20, Санкт-Петербург, 191014',
    coordinates: { latitude: 59.939634, longitude: 30.359659 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [{ url: 'http://www.rusticandblue.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'tp25u2n78l7xznv2kaa4',
    name: 'Rustic and Blue',
    description:
      'Небольшой ресторан с поразительным видом на море, интересные напитки, вкусная еда.',
    address: '95, ถนน วิเศษ Rawai, Mueang Phuket District, Phuket 83130',
    coordinates: { latitude: 7.767342, longitude: 98.316939 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [
      { url: 'https://vk.com/coffee_tchk_spb', title: 'Сайт' },
      { url: 'https://www.instagram.com/coffee.tchk.spb', title: 'Instagram' },
    ],
    authorId: 'r5v1qrpmsvg',
    disabled: false,
    id: 'qudlecas6wgtd42ace3b',
    name: 'Микрокофейня "ТЧК"',
    description:
      'Действительно микро. Очень крутой кофе, шикарные десерты, нет места. Найти сидячее место там могут до 5 человек, остальные 5-10 стоят вплотную на входе. Перед кофейней есть раздолбанные жигули, которые можно использовать как стол.',
    address: 'ул. Мира, 11, Санкт-Петербург, 197101',
    coordinates: { latitude: 59.9592784, longitude: 30.3162732 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '2kumdts8bqd4tlvonco9',
    name: 'Veggie Baan',
    description: 'Питы, хумус, фалафель — просто отлично.',
    address: 'M.7, 87/72, Rawai, Mueang Phuket District, 83130',
    coordinates: { latitude: 7.797481, longitude: 98.32747 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.instagram.com/theheroesbar', title: 'Instagram' },
    ],
    authorId: 'r5v1qrpmsvg',
    disabled: false,
    id: 'o75uhobeunbbszwvz8au',
    name: 'Герои',
    description:
      'Крафтовый бар с очень сытной и вкусной кухней. У них просто обалденные бургеры (есть и веганские с котлетами Beyond Meat), да и всё остальное на должном уровне. Есть бизнес-ланчи.',
    address: 'Трубная ул., 23 стр. 2, Москва, 127051',
    coordinates: { latitude: 55.770766, longitude: 37.625142 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['lunch', 'dinner'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'tiger-lily-spb',
    name: 'Tiger Lily',
    description: 'Обязательно попробуй свинину Хойсин или курицу Кунг Пао.',
    address: 'Итальянская ул., 19, Санкт-Петербург, 190000',
    coordinates: { latitude: 59.936078, longitude: 30.334484 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/pizza22cm', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: '22sm-spb',
    name: 'Пицца 22 сантиметра',
    description: 'Непревзойденная пицца — маленькая, тонкая и очень вкусная.',
    address: 'Большая Конюшенная ул., 2, Санкт-Петербург, 191186',
    coordinates: { latitude: 59.939569, longitude: 30.32411 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch'],
    links: [],
    authorId: null,
    disabled: false,
    id: 'serby-spb',
    name: 'Балканский гурман',
    description: 'Подозрительно дорого, но во время бизнес-ланча — кайф.',
    address: 'Большая Монетная ул., 14а, Санкт-Петербург, 197101',
    coordinates: { latitude: 59.962286, longitude: 30.317621 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [
      { url: 'https://instagram.com/meatarea_chuck', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'chunk-spb',
    name: 'Митерия CHUCK',
    description: 'Стейки, стейки, стейки.',
    address: 'Гороховая ул., 41, Санкт-Петербург, Ленинградская обл., 190031',
    coordinates: { latitude: 59.928963, longitude: 30.321137 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['lunch', 'dinner'],
    links: [
      { url: 'https://www.instagram.com/indisko.spb/', title: 'Instagram' },
    ],
    authorId: null,
    disabled: false,
    id: 'indisko-spb',
    name: 'INDISKO',
    description: 'Индийский еда, трушно острая и очень вкусная.',
    address:
      'Большой проспект Васильевского острова, 16, Санкт-Петербург, 199034',
    coordinates: { latitude: 59.939475, longitude: 30.285367 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://instagram.com/krang_pizza', title: 'Instagram' }],
    authorId: null,
    disabled: false,
    id: 'krang-spb',
    name: 'Krang pizza',
    description: 'Тематическая пиццерия по мотивам Черепашек-ниндзя. ',
    address: 'Гороховая ул., 28, Санкт-Петербург, 191023',
    coordinates: { latitude: 59.930128, longitude: 30.320129 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [{ url: 'https://www.darkoffee.com', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'jpd7j293mgslm0rh9mcl',
    name: "D'ARK Iconsiam",
    description:
      'Ресторан в торговом центре, но с  кофе, замечательными завтраками (свиные ребрышки с яйцами пашот, каково!) и очень красивые сладости.',
    address:
      '299 ICONSIAM Shopping Center, G, UG Floor, Unit no. VG01, VUG, Charoen Nakhon Rd, Klongtonsai, Khlong San, Bangkok 10600',
    coordinates: { latitude: 13.726924, longitude: 100.511385 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['dinner'],
    links: [{ url: 'http://www.jholrestaurant.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'aw3scq663trfgo728xjs',
    name: 'JHOL',
    description:
      'Просто невероятный ресторан индийской кухни — супер-нежная курица и восхитительная грудинка, волшебные десерты.',
    address:
      '7 2 Sukhumvit Soi 18, Khwaeng Khlong Toei, Khlong Toei, Bangkok 10110, Таиланд',
    coordinates: { latitude: 13.733957, longitude: 100.562882 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '0oo9rtozaq9gpwb8qoen',
    name: 'Yellow Lane Cafe',
    description:
      'Во-первых, тут есть соленый лосось (редкость для Таиланда). Во-вторых, тут отличный кофе. В-третьих, тут прекрасные завтраки.',
    address:
      '2, 92 Phahon Yothin 5, Samsen Nai, Phaya Thai, Bangkok 10400, Таиланд',
    coordinates: { latitude: 13.77539, longitude: 100.540004 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '16tcw2xqic4x11aandke',
    name: 'ICI.BKK',
    description: 'Тут готовят удивительные десерты',
    address:
      '24 Soi Sukhumvit 27, Khlong Toei Nuea, Watthana, Bangkok 10110, Таиланд',
    coordinates: { latitude: 13.736812, longitude: 100.565223 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'http://quincebangkok.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'nr499yhig846c6e86hyw',
    name: 'Quince',
    description: 'Средиземноморская кухня, хорошие стейки.',
    address:
      '14/2 Soi Somkid Lumphini, Pathum Wan District, Bangkok 10330, Таиланд',
    coordinates: { latitude: 13.747233, longitude: 100.545581 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '1z36i5oanlkubf5lgnjv',
    name: 'VAREN',
    description: 'Просто хорошее кафе.',
    address:
      '10 12,14 Tri Phet Rd, แขวง วังบูรพา Phra Nakhon, Bangkok 10200, Таиланд',
    coordinates: { latitude: 13.746991, longitude: 100.499538 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [{ url: 'https://www.herringbonebkk.com/qrmenu', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'q3y5i2sngja74xsbimo7',
    name: 'Herringbone',
    description: 'Ресторан при отеле, вкусно, приятный интерьер.',
    address:
      '26/1 Sukhumvit 53 Alley, Khlong Tan Nuea, Watthana, Bangkok 10110, Таиланд',
    coordinates: { latitude: 13.726908, longitude: 100.578155 },
  },
  {
    isExpensive: true,
    isAmazing: true,
    kind: ['dinner'],
    links: [
      { url: 'https://issara-restaurant-bar.business.site/', title: 'Сайт' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'pq63kh3gzuj1lk64o95i',
    name: 'Issara',
    description: 'Один из лучших ресторанов Пхукета. Азиатская фьюжн кухня.',
    address:
      'Kata Noi, 1/34 Katanoi Rd. , Karon, Mueang Phuket District, Kata, Phuket 83100',
    coordinates: { latitude: 7.811611, longitude: 98.297809 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'wik81hqje2cr3iz5mze8',
    name: 'Ryn',
    description: 'Маття и колд-брю — просто отличные место',
    address:
      '8 Krabi, Tambon Talat Nuea, Mueang Phuket District, Phuket 83000, Thailand',
    coordinates: { latitude: 7.88513, longitude: 98.387259 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 's2se5qq4na4hyzfo2fb1',
    name: 'Istanbul',
    description:
      'Турецкая кухня — прекрасное мясо, отличные завтраки и просто божественный хлеб.',
    address: 'Thanon Kata, Kata, Muang, Phuket 83100',
    coordinates: { latitude: 7.816904, longitude: 98.307477 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [{ url: 'http://thaivetro-oldtown.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'hvuzhwh8chwbm1fjhp43',
    name: 'Thaivetro',
    description: 'Лучшее кафе-мороженое в Пхукет Тауне!',
    address: '54 Yaowarat Rd, Talat Yai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.884636, longitude: 98.387533 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '16ih5ee5l1e8pzyq6iqq',
    name: 'Sarnies',
    description: 'Просто бомбические завтраки!',
    address:
      '101-103 Charoen Krung Road 44 North Sathorn, Bang Rak, Bangkok 10500',
    coordinates: { latitude: 13.721212, longitude: 100.514763 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.instagram.com/ateliertapasbar/', title: 'Instagram' },
    ],
    authorId: '5isxkcw5wk6',
    disabled: false,
    id: '9u14zah4e0vi2fmbqgzl',
    name: 'Ателье Tapas & Bar',
    description:
      'Суперприятное испано-мексиканское место. Блюда небольшие, но практически каждое — гастрономический шедевр.\r\nРесторан достаточно маленький, поэтому лучше бронировать. Особенно классные места на двоих — у окошек.\r\nКстати, этот ресторан — личная рекомендация Артемия Панарина 💪',
    address: 'Лахтинская ул., 8, Санкт-Петербург, 197136',
    coordinates: { latitude: 59.9616948134353, longitude: 30.3024396421831 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['dinner'],
    links: [
      { url: 'https://grebeshki.com/', title: 'Сайт' },
      { url: 'https://www.instagram.com/grebeshki/', title: 'Instagram' },
    ],
    authorId: '5isxkcw5wk6',
    disabled: false,
    id: '41qm9rj0lzjh9tgtj8gz',
    name: 'Grebeshki',
    description:
      'Прекрасный ресторан с морепродуктами на набережной. Интерьер, подача, качество продуктов — топ. Иногда проводят тематические вечера и мероприятия.',
    address: 'Арсенальная наб., 1, Санкт-Петербург',
    coordinates: { latitude: 59.95436, longitude: 30.371825 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.instagram.com/teni_neobistro/', title: 'Instagram' },
    ],
    authorId: '5isxkcw5wk6',
    disabled: false,
    id: '0d181yjb9uxlfq2jax47',
    name: 'Тени',
    description:
      'Уютное место с потрясающей кухней. Каждое блюдо — гастрономический шедевр. Вкус, подача, сервис — высший уровень. Шеф Виктор Гусев пришёл из «Мечтателей», это многое объясняет.',
    address: 'Санкт-Петербург, ул. Кирочная, д. 47',
    coordinates: { latitude: 59.942693948184, longitude: 30.379362271048 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      {
        url: 'https://www.instagram.com/myth.coffeebar.hangoutspace/?hl=ru',
        title: 'Instagram',
      },
    ],
    authorId: '3xpv918b2og',
    disabled: false,
    id: '09r7dcjsz1zcjn3nosl9',
    name: 'Myth coffee bar & hangout space',
    description:
      'Минималистичное кафе с приятным видом на тихий двор, вкусными десертами и большим выбором напитков. Отлично подойдёт для отдыха и для работы с компьютером.',
    address: '',
    coordinates: { latitude: 7.849868, longitude: 98.334446 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [
      {
        url: 'https://www.instagram.com/campuscoffeeroaster/',
        title: 'Instagram',
      },
    ],
    authorId: null,
    disabled: false,
    id: 'campus-phuket',
    name: 'CAMPUS COFFEE ROASTER',
    description:
      'Лучшее кафе на Пхукете. Офигенные органические чаи, шикарные десерты.',
    address: '6 Krabi, Talat Nuea, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.884928, longitude: 98.387305 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink'],
    links: [
      { url: 'https://dou-brew-coffee-craft.business.site', title: 'Сайт' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'j1jcldcxnekwod5y5sq6',
    name: 'Dou Brew Coffee & Craft',
    description:
      'Отличный колд-брю, хороший фильтр-кофе и много разных десертов.',
    address:
      '15 Soi Rommani, Tambon Talat Yai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.885505, longitude: 98.389112 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'i7zhtx1c95oenhx4rdog',
    name: 'The Tent Phuket',
    description:
      'Много раных вариантов для завтраков и бранчей, вкусные соки, хороший интервьер.',
    address:
      '16 Thepkrasatree Rd, Tambon Talat Yai, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.884989, longitude: 98.390862 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [{ url: 'https://theearthhotel.co', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 's759y9x88w0cvipvrmby',
    name: 'The Moon Cafe & Eatery',
    description: 'Очень вкусные завтраки, красиво.',
    address: '20/4-5 HauyKeaw Road Chang Puank, Chiang Mai 50300',
    coordinates: { latitude: 18.7979796016065, longitude: 98.9750113415572 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'http://lebistrot-chiangmai.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'or3zsq9ofswlwm0zegtp',
    name: 'Le Bistrot de Chiang Mai',
    description: 'Поразительный французский ресторан. Очень вкусно!',
    address:
      '42 Kampang Din Soi 2 Rd, Amphoe Mueang, Chang Wat 42 Chiang Mai 50100',
    coordinates: { latitude: 18.7854207839822, longitude: 98.9984943441779 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '2yq0et7irmzeordjfeo7',
    name: 'GRAPH Ground',
    description: 'Фильтр-кофе тут просто топ',
    address:
      '41 Siri Mangkalajarn Rd, Tambon Su Thep, Mueang Chiang Mai District, Chiang Mai 50200',
    coordinates: { latitude: 18.7984136443961, longitude: 98.9711019127216 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 's8zanacxbp4ra8h27t50',
    name: 'GRAPH quarter',
    description: 'Совсем маленькое кафе — хороший кофе, вкусные десерты.',
    address:
      '25 Siri Mangkalajarn Rd Lane 13, Tambon Su Thep, เมือง Chiang Mai 50200',
    coordinates: { latitude: 18.7934854241307, longitude: 98.9721945533589 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '5ggu3zboywf1szjconln',
    name: 'Weave Artisan Society',
    description:
      'Огромное пространство с кафе, баром и хостелом. В кафе просто невероятный колд-брю с мёдом.',
    address:
      '12/8 Wua Lai Rd Soi 3, Tambon Hai Ya, Mueang Chiang Mai District, Chiang Mai 50100',
    coordinates: { latitude: 18.7769863918647, longitude: 98.9861887698354 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '1wy1xuy60keiy6t1mu1u',
    name: 'Sun Rays',
    description: 'Совсем маленькое кафе в историческом центре города',
    address:
      '31/1 Samlan Rd Soi 1, Phra Sing, Mueang Chiang Mai District, Chiang Mai 50200',
    coordinates: { latitude: 18.7879723023347, longitude: 98.9798412992866 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [{ url: 'https://instagram.com/h______dining', title: 'Instagram' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'nnyppdarxkqhjee32sx9',
    name: 'h____dining',
    description: 'Очень локальное место с супер необычной кухней',
    address: '4 Soi Sangchai, Phra Khanong, Khlong Toei, Bangkok 10110',
    coordinates: { latitude: 13.7220714653151, longitude: 100.578748070401 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner'],
    links: [{ url: 'https://www.burgerandlobster.com/en', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '96ftd7aus7fx4rk2ulcu',
    name: 'Burger & Lobster',
    description: 'Вкусные бутерброды с мясом лобстера, прямо кайф',
    address: '999 Phloen Chit Rd, Lumphini, Pathum Wan District, Bangkok 10330',
    coordinates: { latitude: 13.7449847655122, longitude: 100.54083633971 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.lenina20.bar/', title: 'Сайт' },
      { url: 'https://www.instagram.com/lenina.20/', title: 'Instagram' },
    ],
    authorId: '5isxkcw5wk6',
    disabled: false,
    id: 'cdp3vmaur1f5f43e3vn1',
    name: 'Lenina 20',
    description:
      'Прекрасный винный гастробар с интересными блюдами и адекватным ценником. Одно из открытий 2020. Особого внимания (неожиданно) достойна конфета ручной работы из белых трюфелей с гелем из рукколы.',
    address: 'Санкт-Петербург, улица Ленина, д. 20',
    coordinates: { latitude: 59.961791, longitude: 30.304212 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.instagram.com/pelmenicafe/', title: 'Instagram' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '7fteodilapwss6ng7qpd',
    name: 'Pelmeni',
    description: 'Ресторан русской кухни с отличным интерьером и вкусной едой.',
    address:
      '504 Patak Rd, Karon, Mueang Phuket District, Chang Wat Phuket 83100',
    coordinates: { latitude: 7.84824172127904, longitude: 98.2954069592027 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [
      { url: 'https://www.instagram.com/mood.phuket/', title: 'Instagram' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'vo1308c7dhursjzld67n',
    name: 'mood',
    description:
      'Милое кафе с приятной террасой, вкусными десертами и отличными соками.',
    address: '8 Hatpatong Rd, Pa Tong, Kathu District, Phuket 83150',
    coordinates: { latitude: 7.89982146410199, longitude: 98.2981991255093 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [
      { url: 'https://www.instagram.com/summerhorsecafe/', title: 'Instagram' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'dlsvd9yqtsoyu9bwrlrl',
    name: 'Summer Horse',
    description: 'Очень уютное кафе с невероятными завтраками',
    address: '2 Soi Hangnokyoong Taladyai, เมือง, Phuket 83000',
    coordinates: { latitude: 7.90122815908236, longitude: 98.3779094784871 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'sf0cxv7vikyc4gi635hn',
    name: 'Dean & Deluca Phuket Old Town',
    description: 'Приятное кафе в старом городе.',
    address: 'Talat Nuea, Mueang Phuket District, Phuket 83000',
    coordinates: { latitude: 7.8933196697709, longitude: 98.3871281130813 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '0ggiohzgdvepvl86citw',
    name: 'Sea Calm Cafe & Bistro',
    description: 'Очень красивое кафе на выезде из национального парка.',
    address: '60/13 ม.1 ซอยในยาง16 สาคู ถลาง Phuket 83110',
    coordinates: { latitude: 8.10216279449815, longitude: 98.3030654912754 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch', 'breakfast'],
    links: [
      { url: 'https://herebkk.com', title: 'Сайт' },
      { url: 'https://www.instagram.com/here_bkk/', title: 'Instagram' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '2266lujcknftfvz8qsff',
    name: 'HERE BKK',
    description: 'Современная индийская кухня — остро, вкусно, красиво',
    address:
      '46, 1 Sukhumvit 53 Alley, Khlong Tan Nuea, Watthana, Bangkok 10110',
    coordinates: { latitude: 13.7276078608327, longitude: 100.578382027972 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'gr2849tuwczryccu639c',
    name: 'a Coffee Roaster by li-bra-ry',
    description: 'Приятная кофейня в креативном кластере Warehouse',
    address: '',
    coordinates: { latitude: 13.7280260038592, longitude: 100.514845754959 },
  },
  {
    isExpensive: true,
    isAmazing: false,
    kind: ['dinner', 'lunch'],
    links: [
      { url: 'https://www.chimchimbangkok.com', title: 'Сайт' },
      { url: 'https://www.instagram.com/chimchimbangkok/', title: 'Instagram' },
    ],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'ihacn5xfg5xe5crizjg5',
    name: 'Chim Chim Bangkok',
    description: 'Хороший ресторан в центре города',
    address:
      'Siam@Siam Design Hotel 865 Rama I Rd, Wang Mai, Pathum Wan District, Bangkok 10330',
    coordinates: { latitude: 13.747692727309, longitude: 100.52691788199 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['dinner', 'lunch'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'hh24brjva3ifol2335jy',
    name: 'Sweet Pista',
    description:
      'Просто невероятная паста, вкусное мясо, отличные десерты. Расположен в арт-кластере Warehouse.',
    address:
      'Warehouse 30, 52, โกดัง 9 Captain Bush Ln, Bang Rak, Bangkok 10500',
    coordinates: { latitude: 13.7278771030705, longitude: 100.514848071164 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'breakfast'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: '3calyra4kd70wjnooq16',
    name: 'Tiny Cup Cafe',
    description:
      'Милое кафе с приятным интерьером и замечательным фильтр-кофе.',
    address: 'Thonglor Rd, Khlong Tan Nuea, Watthana, Bangkok 10110',
    coordinates: { latitude: 13.7376801708798, longitude: 100.583702080131 },
  },
  {
    isExpensive: false,
    isAmazing: false,
    kind: ['bite-drink', 'lunch', 'breakfast'],
    links: [{ url: 'https://bartelsbangkok.com/', title: 'Сайт' }],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'nvdwfmcybtxj9saf2wuw',
    name: 'Bartels Craft Bread, Coffee & Juicery',
    description:
      'Лучшие бутерброды Бангкока! Бонусом — вкусные соки и быстрый интернет.',
    address:
      '760, 1 Sukhumvit Rd, Khwaeng Khlong Tan, Khlong Toei, Bangkok 10110',
    coordinates: { latitude: 13.7270912590638, longitude: 100.574493383839 },
  },
  {
    isExpensive: false,
    isAmazing: true,
    kind: ['bite-drink'],
    links: [],
    authorId: 'ii4e9v9wq74',
    disabled: false,
    id: 'sjckahnhkujdo66e9pza',
    name: "Y'EST WORKS coffee bar",
    description: 'Вероятно, лучший кофе в городе',
    address: '732 Sukhumvit Rd, Khlong Tan, Khlong Toei, Bangkok 10110',
    coordinates: { latitude: 13.728038259744, longitude: 100.573212599181 },
  },
];
